//This File is Auto-Generated by the editor window
//Date of creation: 27/05/2020 08:55:03
namespace Opsive.UltimateInventorySystem.DatabaseNames
{
    public static class DemoInventoryDatabaseNames
    {
        //ItemCategories 

        public static class Viewable
        {
            public const string name = "Viewable";//ItemCategory 

            //Attributes
            public const string categoryIcon = "CategoryIcon";//Sprite
            public const string description = "Description";//String
            public const string icon = "Icon";//Sprite

            //Item Definitions
        }

        public static class Pickupable
        {
            public const string name = "Pickupable";//ItemCategory 

            //Attributes
            public const string pickupPrefab = "PickupPrefab";//GameObject

            //Item Definitions
        }

        public static class Shoppable
        {
            public const string name = "Shoppable";//ItemCategory 

            //Attributes
            public const string buyPrice = "BuyPrice";//CurrencyAmounts
            public const string sellPrice = "SellPrice";//CurrencyAmounts

            //Item Definitions
        }

        public static class NormalItem
        {
            public const string name = "Normal Item";//ItemCategory 

            //Attributes

            //Item Definitions
        }

        public static class EquippableItem
        {
            public const string name = "Equippable Item";//ItemCategory 

            //Attributes
            public const string equipmentPrefab = "EquipmentPrefab";//GameObject

            //Item Definitions
        }

        public static class Material
        {
            public const string name = "Material";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string wood = "Wood";//ItemDefinition
            public const string water = "Water";//ItemDefinition
            public const string healWeed = "Heal Weed";//ItemDefinition
            public const string titaniumIngot = "Titanium Ingot";//ItemDefinition
            public const string titaniumNugget = "Titanium Nugget";//ItemDefinition
            public const string magicalPowder = "Magical Powder";//ItemDefinition
        }

        public static class Consumable
        {
            public const string name = "Consumable";//ItemCategory 

            //Attributes
            public const string healAmount = "HealAmount";//Int32

            //Item Definitions
            public const string potion = "Potion";//ItemDefinition
            public const string bigPotion = "Big Potion";//ItemDefinition
        }

        public static class Weapons
        {
            public const string name = "Weapons";//ItemCategory 

            //Attributes
            public const string baseAttack = "BaseAttack";//Int32
            public const string attack = "Attack";//Int32

            //Item Definitions
        }

        public static class Sword
        {
            public const string name = "Sword";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string woodenSword = "Wooden Sword";//ItemDefinition
            public const string greatSword = "Great Sword";//ItemDefinition
            public const string ironSword = "Iron Sword";//ItemDefinition
        }

        public static class Armor
        {
            public const string name = "Armor";//ItemCategory 

            //Attributes
            public const string baseDefense = "BaseDefense";//Int32
            public const string defense = "Defense";//Int32

            //Item Definitions
        }

        public static class KeyItem
        {
            public const string name = "Key Item";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string chestKey = "Chest Key";//ItemDefinition
            public const string gateKey = "Gate Key";//ItemDefinition
        }

        public static class HotbarItem
        {
            public const string name = "Hotbar Item";//ItemCategory 

            //Attributes
            public const string categoryIcon = "CategoryIcon";//Sprite

            //Item Definitions
        }

        public static class HeadWear
        {
            public const string name = "Head Wear";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string knightHelmet = "Knight Helmet";//ItemDefinition
            public const string hood = "Hood";//ItemDefinition
        }

        public static class ChestWear
        {
            public const string name = "Chest Wear";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string knightArmor = "Knight Armor";//ItemDefinition
            public const string leatherArmor = "Leather Armor";//ItemDefinition
        }

        public static class LegWear
        {
            public const string name = "Leg Wear";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string knightBoots = "Knight Boots";//ItemDefinition
            public const string leatherBoots = "Leather Boots";//ItemDefinition
        }

        public static class ItemHolder
        {
            public const string name = "Item Holder";//ItemCategory 

            //Attributes
            public const string slotCount = "SlotCount";//Int32
            public const string slots = "Slots";//ItemAmounts

            //Item Definitions
        }

        public static class Upgradable
        {
            public const string name = "Upgradable";//ItemCategory 

            //Attributes
            public const string slotCount = "SlotCount";//Int32
            public const string slots = "Slots";//ItemAmounts

            //Item Definitions
        }

        public static class UpgradeItem
        {
            public const string name = "Upgrade Item";//ItemCategory 

            //Attributes
            public const string prefix = "Prefix";//String
            public const string suffix = "Suffix";//String
            public const string boostConstant = "BoostConstant";//Int32
            public const string boostMultiplier = "BoostMultiplier";//Single

            //Item Definitions
            public const string boostRune = "Boost Rune";//ItemDefinition
            public const string runeOfDoom = "Rune of Doom";//ItemDefinition
            public const string amazingRune = "Amazing Rune";//ItemDefinition
        }

        public static class Uncategorized
        {
            public const string name = "Uncategorized";//ItemCategory 

            //Attributes

            //Item Definitions
        }

        public static class ItemBag
        {
            public const string name = "Item Bag";//ItemCategory 

            //Attributes

            //Item Definitions
            public const string surpriseBox = "Surprise Box";//ItemDefinition
        }

        public static class Wand
        {
            public const string name = "Wand";//ItemCategory 

            //Attributes
            public const string projectilePrefab = "ProjectilePrefab";//GameObject
            public const string numOfProjectiles = "NumOfProjectiles";//Int32

            //Item Definitions
            public const string fireWand = "Fire Wand";//ItemDefinition
            public const string wizardWand = "Wizard Wand";//ItemDefinition
            public const string iceWand = "Ice Wand";//ItemDefinition
        }

        public static class UsableEquippableItem
        {
            public const string name = "Usable Equippable Item";//ItemCategory 

            //Attributes
            public const string usableItemPrefab = "UsableItemPrefab";//GameObject

            //Item Definitions
        }

        public static class Throwable
        {
            public const string name = "Throwable";//ItemCategory 

            //Attributes
            public const string throwablePrefab = "ThrowablePrefab";//GameObject

            //Item Definitions
            public const string bomb = "Bomb";//ItemDefinition
            public const string bigBomb = "Big Bomb";//ItemDefinition
        }

        public static class Animated
        {
            public const string name = "Animated";//ItemCategory 

            //Attributes
            public const string animationID = "AnimationID";//Int32

            //Item Definitions
        }

        public static class UsableItem
        {
            public const string name = "Usable Item";//ItemCategory 

            //Attributes
            public const string categoryIcon = "CategoryIcon";//Sprite

            //Item Definitions
        }

        //Item Definitions
        public const string potion = "Potion";//ItemDefinition
        public const string wood = "Wood";//ItemDefinition
        public const string woodenSword = "Wooden Sword";//ItemDefinition
        public const string greatSword = "Great Sword";//ItemDefinition
        public const string bigPotion = "Big Potion";//ItemDefinition
        public const string knightArmor = "Knight Armor";//ItemDefinition
        public const string water = "Water";//ItemDefinition
        public const string healWeed = "Heal Weed";//ItemDefinition
        public const string knightHelmet = "Knight Helmet";//ItemDefinition
        public const string knightBoots = "Knight Boots";//ItemDefinition
        public const string boostRune = "Boost Rune";//ItemDefinition
        public const string runeOfDoom = "Rune of Doom";//ItemDefinition
        public const string amazingRune = "Amazing Rune";//ItemDefinition
        public const string hood = "Hood";//ItemDefinition
        public const string leatherArmor = "Leather Armor";//ItemDefinition
        public const string leatherBoots = "Leather Boots";//ItemDefinition
        public const string surpriseBox = "Surprise Box";//ItemDefinition
        public const string fireWand = "Fire Wand";//ItemDefinition
        public const string wizardWand = "Wizard Wand";//ItemDefinition
        public const string ironSword = "Iron Sword";//ItemDefinition
        public const string titaniumIngot = "Titanium Ingot";//ItemDefinition
        public const string titaniumNugget = "Titanium Nugget";//ItemDefinition
        public const string iceWand = "Ice Wand";//ItemDefinition
        public const string chestKey = "Chest Key";//ItemDefinition
        public const string gateKey = "Gate Key";//ItemDefinition
        public const string bomb = "Bomb";//ItemDefinition
        public const string magicalPowder = "Magical Powder";//ItemDefinition
        public const string bigBomb = "Big Bomb";//ItemDefinition

    }
}