#if USE_YARN2

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/mmcclenney/workspace/zanzo/repos/Yarn_2_Import/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Editor/Tools/Importers/Yarn/ANTLR/PixelCrushersYarnSpinnerParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
// Ignore CLS compliance
#pragma warning disable 3021

namespace PixelCrushers.DialogueSystem.Yarn {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PixelCrushersYarnSpinnerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IPixelCrushersYarnSpinnerParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDialogue([NotNull] PixelCrushersYarnSpinnerParser.DialogueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDialogue([NotNull] PixelCrushersYarnSpinnerParser.DialogueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.file_hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_hashtag([NotNull] PixelCrushersYarnSpinnerParser.File_hashtagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.file_hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_hashtag([NotNull] PixelCrushersYarnSpinnerParser.File_hashtagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode([NotNull] PixelCrushersYarnSpinnerParser.NodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode([NotNull] PixelCrushersYarnSpinnerParser.NodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] PixelCrushersYarnSpinnerParser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] PixelCrushersYarnSpinnerParser.HeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] PixelCrushersYarnSpinnerParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] PixelCrushersYarnSpinnerParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PixelCrushersYarnSpinnerParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PixelCrushersYarnSpinnerParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_statement([NotNull] PixelCrushersYarnSpinnerParser.Line_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Line_formatted_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Line_formatted_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashtag([NotNull] PixelCrushersYarnSpinnerParser.HashtagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashtag([NotNull] PixelCrushersYarnSpinnerParser.HashtagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_condition([NotNull] PixelCrushersYarnSpinnerParser.Line_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.line_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_condition([NotNull] PixelCrushersYarnSpinnerParser.Line_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpParens([NotNull] PixelCrushersYarnSpinnerParser.ExpParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpParens([NotNull] PixelCrushersYarnSpinnerParser.ExpParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpMultDivMod([NotNull] PixelCrushersYarnSpinnerParser.ExpMultDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpMultDivMod([NotNull] PixelCrushersYarnSpinnerParser.ExpMultDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpComparison([NotNull] PixelCrushersYarnSpinnerParser.ExpComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpComparison([NotNull] PixelCrushersYarnSpinnerParser.ExpComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpNegative([NotNull] PixelCrushersYarnSpinnerParser.ExpNegativeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpNegative([NotNull] PixelCrushersYarnSpinnerParser.ExpNegativeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAndOrXor([NotNull] PixelCrushersYarnSpinnerParser.ExpAndOrXorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAndOrXor([NotNull] PixelCrushersYarnSpinnerParser.ExpAndOrXorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAddSub([NotNull] PixelCrushersYarnSpinnerParser.ExpAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAddSub([NotNull] PixelCrushersYarnSpinnerParser.ExpAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpNot([NotNull] PixelCrushersYarnSpinnerParser.ExpNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpNot([NotNull] PixelCrushersYarnSpinnerParser.ExpNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpValue([NotNull] PixelCrushersYarnSpinnerParser.ExpValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpValue([NotNull] PixelCrushersYarnSpinnerParser.ExpValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpEquality([NotNull] PixelCrushersYarnSpinnerParser.ExpEqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpEquality([NotNull] PixelCrushersYarnSpinnerParser.ExpEqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNumber([NotNull] PixelCrushersYarnSpinnerParser.ValueNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNumber([NotNull] PixelCrushersYarnSpinnerParser.ValueNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTrue([NotNull] PixelCrushersYarnSpinnerParser.ValueTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTrue([NotNull] PixelCrushersYarnSpinnerParser.ValueTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueFalse([NotNull] PixelCrushersYarnSpinnerParser.ValueFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueFalse([NotNull] PixelCrushersYarnSpinnerParser.ValueFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueVar([NotNull] PixelCrushersYarnSpinnerParser.ValueVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueVar([NotNull] PixelCrushersYarnSpinnerParser.ValueVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueString([NotNull] PixelCrushersYarnSpinnerParser.ValueStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueString([NotNull] PixelCrushersYarnSpinnerParser.ValueStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNull([NotNull] PixelCrushersYarnSpinnerParser.ValueNullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNull([NotNull] PixelCrushersYarnSpinnerParser.ValueNullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueFunc([NotNull] PixelCrushersYarnSpinnerParser.ValueFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueFunc([NotNull] PixelCrushersYarnSpinnerParser.ValueFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] PixelCrushersYarnSpinnerParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] PixelCrushersYarnSpinnerParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] PixelCrushersYarnSpinnerParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] PixelCrushersYarnSpinnerParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] PixelCrushersYarnSpinnerParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] PixelCrushersYarnSpinnerParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_clause([NotNull] PixelCrushersYarnSpinnerParser.If_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_clause([NotNull] PixelCrushersYarnSpinnerParser.If_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_if_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_if_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_if_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_if_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_clause([NotNull] PixelCrushersYarnSpinnerParser.Else_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_statement([NotNull] PixelCrushersYarnSpinnerParser.Set_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_statement([NotNull] PixelCrushersYarnSpinnerParser.Set_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_statement([NotNull] PixelCrushersYarnSpinnerParser.Call_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_statement([NotNull] PixelCrushersYarnSpinnerParser.Call_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand_statement([NotNull] PixelCrushersYarnSpinnerParser.Command_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand_statement([NotNull] PixelCrushersYarnSpinnerParser.Command_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Command_formatted_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.command_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand_formatted_text([NotNull] PixelCrushersYarnSpinnerParser.Command_formatted_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortcut_option_statement([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_option_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortcut_option_statement([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_option_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortcut_option([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.shortcut_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortcut_option([NotNull] PixelCrushersYarnSpinnerParser.Shortcut_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare_statement([NotNull] PixelCrushersYarnSpinnerParser.Declare_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PixelCrushersYarnSpinnerParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare_statement([NotNull] PixelCrushersYarnSpinnerParser.Declare_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>jumpToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpToNodeName([NotNull] PixelCrushersYarnSpinnerParser.JumpToNodeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>jumpToNodeName</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpToNodeName([NotNull] PixelCrushersYarnSpinnerParser.JumpToNodeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>jumpToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpToExpression([NotNull] PixelCrushersYarnSpinnerParser.JumpToExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>jumpToExpression</c>
	/// labeled alternative in <see cref="PixelCrushersYarnSpinnerParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpToExpression([NotNull] PixelCrushersYarnSpinnerParser.JumpToExpressionContext context);
}
} // namespace PixelCrushers.DialogueSystem.Yarn

#endif
